### ISSUE TITLE
Custom config archivist entries don't seem to override default config.

### ISSUE THREAD

**Issue by Tatsujinichi** [mage/mage#124]
npm install mage --create --typescript --prefix my-gameserver

> config/custom.yaml

```yaml
archivist:
    vaults:
        # Our vaults, augment this with as many as you need.
        # You should take care to name them appropriately given the context of how they will be used.
        volatileVault:
            type: memory
        userVault:
            type: file
            config:
                path: ./filevault/userVault
        tableVault:
            type: file
            config:
                path: ./filevault/tableVault

    # When doing "list" operations, we will attempt each mentioned vault until successful
    listOrder:
        - userVault
        - tableVault

    # When doing "get" operations, we will attempt each mentioned vault until successful
    readOrder:
        - volatileVault
        - userVault
        - tableVault

    # When doing "add/set/touch/del" operations, we will write to each mentioned vault in the given order
    writeOrder:
        - client
        - volatileVault
        - userVault
        - tableVault
```

add to file

>lib/archivist/index.ts
```javascript
exports.table = <mage.archivist.ITopic> {
  index: ['tableId'],
  vaults: {
    tableVault: {
    }
  }
};
```

Then run `npm run archivist-create`;

```
m-18602 - 16:26:19.071     <debug> [MAGE archivist] Vault "tableVault" is not in list/read/write-order, skipping.
m-18602 - 16:26:19.075 <emergency> [MAGE archivist] None of the mentioned vaults for topic "table" is available.
  data: {
    "file": "configuration.js",
    "line": 620,
    "offset": 10,
    "type": "Error",
    "stack": [
      "node_modules/mage/lib/archivist/configuration.js:620:10",
      "Array.forEach (native)",
      "registerTopics (node_modules/mage/lib/archivist/configuration.js:596:9)",
      "Object.exports.setup (node_modules/mage/lib/archivist/configuration.js:675:3)",
      "EventEmitter.exports.setup (node_modules/mage/lib/archivist/index.js:20:16)",
      "setupArchivist (node_modules/mage/lib/tasks/serve.js:23:23)",
      "node_modules/async/lib/async.js:610:21",
      "node_modules/async/lib/async.js:249:17",
      "iterate (node_modules/async/lib/async.js:149:13)",
      "node_modules/async/lib/async.js:160:25"
    ]
  }
```

Copying the config from the custom.yaml to default.yaml fixes this.

I expect config in the custom config to override or add to the default config.
