### ISSUE TITLE
Archivist breaks with Couchbase 5.x

### ISSUE THREAD

**Issue by christopherobin** [mage/mage#169]
One of the new change in CB 5.x is that access to a bucket now requires to authenticate with the cluster using the new RBAC (Role Based Access Control) mechanism.

This just requires to add a call to `cluster.authenticate` right after creating the cluster object in the vault.

### Resources

https://developer.couchbase.com/documentation/server/5.0/release-notes/relnotes.html
https://developer.couchbase.com/documentation/server/5.0/introduction/whats-new.html
https://developer.couchbase.com/documentation/server/5.0/security/security-authorization.html#authorization
https://developer.couchbase.com/documentation/server/current/sdk/nodejs/start-using-sdk.html

**Comment by stelcheck** [comment]
@christopherobin apologies for the late response. 

Would you be able to PR that one in? And can this behavior be backward compatible with couchbase 4?

**Comment by christopherobin** [comment]
So the `couchnode` API does not provide any way to know whether or not we should authenticate, so this will have to be configuration driven, maybe something like this:

```yaml
archivist:
    vaults:
        myVault:
            type: couchbase
            config:
                flagStyle: node-memcached
                options:
                    hosts: [ "localhost:8091" ]
                    bucket: volatile
                    // new section here
                    authenticate:
                        username: admin
                        password: whatever
                create:
                    adminUsername: admin
                    adminPassword: whatever
                    bucketType: memcached
                    ramQuotaMB: 100
```

The issue though is that we duplicate the auth configuration between each bucket and even between the create and options area. Not really pretty :(

**Comment by stelcheck** [comment]
My guess would be that we should be able to do something like that:

```yaml
archivist:
    vaults:
        myVault:
            type: couchbase
            config:
                flagStyle: node-memcached
                options:
                    hosts: [ "localhost:8091" ]
                    bucket: volatile
                    username: admin
                    password: whatever
                create:
                    bucketType: memcached
                    ramQuotaMB: 100
```

And throw an error if create is specified but username or password is missing.
