### ISSUE TITLE
archivist:create is now broken for couchbase

### ISSUE THREAD

**Issue by Yuuki77** [mage/mage#227]
Using couchbase 4.

```yaml
archivist:
  vaults:
    volatileVault:
      type: couchbase
      config:
        create:
          adminUsername: admin
          adminPassword: hello
          bucketType: couchbase
          ramQuotaMB: 100
          replicaNumber: 0
          bucketType: memcached
        options:
          scheme: couchbase
          hosts:
            - localhost:8091
          bucket: volatile
```

When I call `npm run archivist:create`, I get the following error:

```plaintext
Failed to load MAGE application: CouchbaseError: Authentication failed. You may have provided an invalid username/password combination
```
